import { DM_Sans } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";

const dm_sans = DM_Sans({
  subsets: ["latin"],
  weight: ['400', '700']
});

export const metadata = {
  title: "Character Counter",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${dm_sans.className}  antialiased`}
      >
        <ThemeProvider attribute="class">
        {children}
        </ThemeProvider>
   
      </body>
    </html>
  );
}
